import type { Metadata } from "next";
import "./globals.css";

import { Space_Grotesk, Manrope, Orbitron } from "next/font/google";

export const space_grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space_grotesk",
});

export const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from "@/components/Header";

import Footer from "@/components/Footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${space_grotesk.variable} ${manrope.variable} ${orbitron.variable} antialiased bg-[#050505] text-white `}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
